DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS solutions;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS tag_solution;

CREATE TABLE users(
    user_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email VARCHAR(320) NOT NULL,
    name VARCHAR(50) NOT NULL,
    picture VARCHAR(100),
    UNIQUE(email)
);

CREATE TABLE solutions(
    solution_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(50) NOT NULL,
    link VARCHAR(100) NOT NULL,
    source VARCHAR(50) NOT NULL,
    my_solution TEXT NOT NULL,
    perfect_solution TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE tags(
    tag_id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(50) NOT NULL
);

CREATE TABLE tag_solution(
    tag_id INT NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
    solution_id INTEGER NOT NULL REFERENCES solutions(solution_id) ON DELETE CASCADE
);